theme: jekyll-theme-leap-day
name: ZNProjects
title: ZNProjects
description: Software is beautiful again!
google_analytics: UA-12761202-2
repository: zakaluka/zakaluka.github.io
github:
  repository_url: https://znprojects.com
